_target_: rationai.mlkit.lightning.loggers.MLFlowLogger
tracking_uri: http://mlflow.rationai-mlflow:5000/
experiment_name: ${metadata.experiment_name}
run_name: ${metadata.run_name}
tags:
  mlflow.user: ${metadata.user}
  mlflow.note.content: ${metadata.description}
